[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pangi_token = "BDSjfUUwEVHxJ3WLxHgNbKddCXEFVX3thS72fg6F4EaA"
pangi_vault = "5ghkR1LyUMA4K8Dhit2ssqnBbWsZv3sWgvbFSoTKnhw2"
pangi_nft = "etpBw57TYbPLMiTVB16iRUNKoSvfux2Gi1Mf9omXnYE"
special_distribution = "bPtCiRVMtoNMxt5r7pyrzRe6YWKB7eJ7fy1LRLMj7Qq"

[programs.devnet]
pangi_token = "BDSjfUUwEVHxJ3WLxHgNbKddCXEFVX3thS72fg6F4EaA"
pangi_vault = "5ghkR1LyUMA4K8Dhit2ssqnBbWsZv3sWgvbFSoTKnhw2"
pangi_nft = "etpBw57TYbPLMiTVB16iRUNKoSvfux2Gi1Mf9omXnYE"
special_distribution = "bPtCiRVMtoNMxt5r7pyrzRe6YWKB7eJ7fy1LRLMj7Qq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/pangi-token",
    "programs/pangi-vault",
    "programs/pangi-nft",
    "programs/special-distribution"
]
